### DISCUSSION TITLE
File Based Configuration

### DISCUSSION THREAD

**Discussion by dgduncan** [mochi-mqtt/server#281] [Ideas]
Wanted to start a new thread as to not clutter up the roadmap discussion.
I have implemented a completely barebones implementation of file based config using a yml file and a flag passed in when running `main.go` [here](https://github.com/dgduncan/mqtt/tree/feature/basic-file-config).  I have some questions that I would love to get everyones opinion on so I know where to go from here:

Architecture:
- Create separate `mqtt.Options` struct or simply tag the current struct? 
- Should this live in it's own new package, say `config` or `configuration` where a user of the library can choose to use the functionality from the package or should it be integrated into the `server` directly.
- Should I update the `Dockerfile` to include a env/flag so when running the default `Dockerfile` a user can simply include a filepath or filename?

Features:
I want to know what everyone thinks is mandatory to make this useful, and a nice to have. Here are my opinions but I want to know more.

Mandatory:

- Server configuration (i.e a file copy of what `Options` looks like when creating a server`)
- Ports
- Log level

Useful:
- SSL with basic certificate functionality (i.e file/filepath)
- Basic Hooks

Nice to have
- Non standard hooks

Please feel free mention anything else and give ideas!

Hooks
- [x] AllowAll
- [ ] Access Ledger
- [ ] Bolt
- [ ] Badger
- [ ] Redis
- [ ] Debug

Listeners

- [x] Healthcheck
- [x] Stats
- [x] TCP
- [x] Websocket
- [ ] UnixSock
- [ ] Net
- [x] TLS

Servers
- [x] Capabilities

**Comment by werbenhu** [comment]
I suggest that the relevant configurations inside DefaultServerCapabilities can be written to the configuration file, such as MaximumClientWritesPending. When the number of connections reaches a certain level, these parameters have a significant impact on memory. By placing them in the configuration file, users can fine-tune these parameters according to their specific scenarios.

**Comment by dgduncan** [comment]
I have added a working version, albeit not a feature complete implementation, of file based configuration [here](https://github.com/dgduncan/mqtt/tree/feature/basic-file-config). here are some of the key choices I made and would love any considerations.

- Static config file name `mochi_config.yml`
- New package called `config` where `Configure` returns a `*mqtt.Server` instance. Will most likely create a new `Config` interface to allow new `Configs` to be created say from `std.in`, `remote server`, etc
- Server capabilities is the same struct used by the `server` but with `yaml` tags that have been changed to snake case to fit with the more common, but not standard, `yaml` styling
- New "smart" defaults created such that if a user only adds a few config fields to the `mochi_config.yml` file, defaults are created for the other fields
- default mochi docker should look for `mochi_config.yml` file but will not require it. This should lower barrier of entry to using the docker file as  I have found config files can be confusing to new users compared to allowing to run with a very basic default to get a user up and running
- Config file is accessible via mounting a file volume when starting the image.

here is an example of the `docker` command:
`docker run -p 1883:1883 -p 8081:8081 -v ${PWD}/mochi_config.yml:/mochi_config.yml test_docker:v0.0.1`

**Reply by SimonMacIntyre** [reply]
Do you guys think it is possible to host a docker image, so that we do not need to clone the repository at all via git submodules? For example the mqtt service is just one of many services in our applications, and we want to host it on the network alongside them. However, for example just how we would never have postgres source code cloned into our actual project, it is inconvenient to require the source code in our project for the MQTT broker. 

I'm not sure if there are limitations that make this impossible, however I envisioned a path where we just reference the hosted dockerfile (essentially holding the source code), which we then configure with file mounting alone. 

I am new to Golang, so I understand maybe this is impossible since we are building the binary and I suppose for something like I am imagining to work it would require basically having the source in the dockerfile raw, then we mount our config files into it and it compiles when starting the container or something like this? 

Forgive me if my terminology is all out of what or if this type of setup is just impossible with Golang in this way. 

For example, we used to use EMQX, and it worked in this exact fashion, where we just referenced the EMQX docker image, dropped our config files in, and it works that way (no need to clone the repository). 

Let me know if this is either impossible, or potentially an option in a later phase, or if I simply misunderstand fundamentals here! 

Thanks for this awesome work 🙏

**Reply by dgduncan** [reply]
@SimonMacIntyre The situation you described here is exactly the reason for the introduction of file based configuration. The end goal of the first iteration is to have a docker image hosted on Docker Hub and the config file mounted to the container in this example command `docker run -p 1883:1883 -p 8081:8081 -v ${PWD}/mochi_config.yml:/mochi_config.yml test_docker:v0.0.1` in which `test_docker:v0.0.1` would be hosted somewhere where you do not need to build the image from source.

Would you mind letting me know what are some of the configurations that are non-negotiable for it to be useful? The first iteration will most likely not contain all available configurations in terms of hooks and TLS.

**Reply by SimonMacIntyre** [reply]
Got it, thank you! 

Having a public hosted docker file would be a fantastic start even without any other features. Since I could at least stop cloning the repository, and focus only on copying my files into it at build time, maybe. I know I can obviously clone the repo and push my own images, it's just nice when its part of the release process here in this repo and I can just always find the latest release tagged docker image.

But for the dream scenario, in docker compose in my case, I would need a way to dynamically add custom hooks, define the services (wss + mqtts and their ports), and mount the certificates. 

* The hooks are used in my basic business cases, for example authenticating users against a different service.
* TLS I could potentially live without, I think, with load balancing/SSL termination I might not need it, I am still focused on local development of this project so I haven't yet gotten to real life deploy cases, where I might have lots of new feedback. Planning to eventually deploy it as a container in a kubernetes cluster.
* Then I think the most basic thing people would need is just defining the protocol and port to serve from basically


This is an example of how I would try to use it:
```yaml
  mqtt:
    image: mochi-mqtt/server
    ports:
      - 8883:8883
      - 8882:8882
      - 8080:8080
    environment:
      VIRTUAL_HOST: fake.host
      WSS: true
      WSS_PORT: 8882
      MQTTS: true
      MQTTS_PORT: 8883
      DASHBOARD: true
      DASHBOARD_PORT: 8080
    volumes:
      - certs/fake.crt:/etc/ssl/certs/cert.pem:ro
      - certs/fake.key:/etc/ssl/certs/key.pem:ro
      - hooks/:/some-hook-folder/
      - /mochi_config.json:/mochi_config.json
```

As a Golang noob, I am thinking I could make a very awful implementation that does this but it wouldn't be of the quality I would assume is possible of reaching haha. Basically:
* Hardcode a few ports/listeners and override them with env vars
* Hardcode where TLS key/cert files need to be dropped, used if the WSS/MQTTS is enabled
* Hardcode some hooks folder that gets basically iterated over and dumped into the right place for Mochi, who then adds the hooks all to the server

It's just, I'm sure it is much more complicated than that and if it even was possible this way, maybe is not professional or robust, or future proof, etc! 

I just looked through your fork, and it looks like its heading in an amazing direction!

**Reply by SimonMacIntyre** [reply]
Here was the working docker compose that we used when we were using EMQX! Maybe you will find it inspiring, definitely does not need to match it but just thought you might find it interesting for reference:

```yaml
  mqtt:
    image: emqx/emqx
    ports:
      - 2083:2083 #ssl tcp
      - 2053:443 #wss
      - 2087:2087 #https dashboard
      - 18083:18083 #http dashboard
    environment:
      - VIRTUAL_HOST=mqtt.docker
    volumes:
      - ~/certs/mqtt.docker.crt:/opt/emqx/etc/certs/cert.pem
      - ~/certs/mqtt.docker.key:/opt/emqx/etc/certs/key.pem
      - ~/certs/rootCA.pem:/opt/emqx/etc/certs/cacert.pem
      - emqx:/opt/emqx/data #this is a docker volume, similar to how they are used for example mysql data
      - .local/mqtt/emqx.conf:/opt/emqx/etc/emqx.conf #this is the config file
```

Here is an example snippet from the config file:
```yaml
listeners.ssl.default {
    bind = "0.0.0.0:2083"
    max_connections = 512000
    ssl_options {
        keyfile = "/opt/emqx/etc/certs/key.pem"
        certfile = "/opt/emqx/etc/certs/cert.pem"
        cacertfile = "/opt/emqx/etc/certs/cacert.pem"
    }
}

listeners.wss.default {
    bind = "0.0.0.0:443"
    max_connections = 512000
    websocket.mqtt_path = "/mqtt"
    ssl_options {
        keyfile = "/opt/emqx/etc/certs/key.pem"
        certfile = "/opt/emqx/etc/certs/cert.pem"
        cacertfile = "/opt/emqx/etc/certs/cacert.pem"
    }

```

There is a reason we ditched EMQX and fully invested in Mochi! We <3 Mochi and the hooks based architecture! Only sharing incase any of this inpsires ideas.

**Reply by dgduncan** [reply]
I am super happy to hear that you are liking it! From the direction I am currently working in, I feel like all but the last use case of including a `hooks` folder that could be inserted at runtime are either already implemented or on the short list of implementation for this version of the feature. The idea of drop in custom hooks is an interesting concept that would need further exploration into its' feasibility or how it would end up looking.

**Reply by SimonMacIntyre** [reply]
That hooks folder idea may have been a bad one haha, I am just interested in a way in general to add custom hooks, and am unsure the best approach!

**Reply by dgduncan** [reply]
I have started a discussion thread for the use case [here](https://github.com/orgs/mochi-mqtt/discussions/285) if you would like to see how the discussion develops overtime :) Thank you for all the input!

**Reply by SimonMacIntyre** [reply]
No, thank you!

**Reply by dgduncan** [reply]
@SimonMacIntyre I have pushed a very basic docker image to docker hub. If you are up to it I would love for you to test it out to see how it works for you. Currently it supports basic TLS where you can mount file very similar to the EMQX example above. 
`docker pull dgduncan93/mochi-server-file-config:v0.0.1`
[Docker Registry Link](https://hub.docker.com/repository/docker/dgduncan93/mochi-server-file-config/general)

Please refer to these two files for configuration examples
[file](https://github.com/dgduncan/mqtt/blob/feature/basic-file-config/mochi_config.yml)
[code](https://github.com/dgduncan/mqtt/blob/6ef6cb56c24cca79fed13f6c3ff94af44a6cf838/configs/file/file.go#L28C1-L69)

I will be updating this testing one periodically until we get everything set up for the official image. Please let me know if you have any questions!

**Reply by SimonMacIntyre** [reply]
Will try to report back in the next couple days! Thanks!

**Reply by dgduncan** [reply]
One thing to note that isn't shown in that above `file` link is that for the TLS config there is indeed a config for the `cacert` in the form of `"cacert_file"`

**Reply by dgduncan** [reply]
@SimonMacIntyre Just checking it to see if you have had a moment to check out the changes to see if they fit your needs and/or need any assistance?

**Reply by SimonMacIntyre** [reply]
It is great, and should work for a lot of docker-first use cases who just need a quick broker up and running in a local setting.

~~One small issue is the docker does not seem to persist but rather seems to run and die.~~

~~The log that seems to be missing, compared to my local dockerfile is this:~~
`2023-09-14 10:03:37 time=2023-09-14T13:03:37.916Z level=INFO msg="mochi mqtt starting" version=2.4.0`

Ignore that! Was my fault for misconfiguration of having my other broker running on a conflicting port. 🤓 It runs great!

But my use case requires custom hook functionality, which means I need to keep doing my workaround of cloning the repository so that I can drop in my hooks in the pre-compiled phase. There is no way around this for any type of production use case where you at least need an auth hook -- and I think it is very common to want to authenticate against your own mechanism (like your own backend server, or something like that). 

For example, devices need to authenticate, but something like the ledger doesn't really work for cases where the auth is dynamic in fashion (you do not know ahead of time every user of your broker, but you do need to auth them for example check a token, or even a user/pass against a backend, etc)

I don't think my use case is any blocker for this great work being merged, it's a great foundation for docker use cases to build upon!

**Reply by dgduncan** [reply]
Awesome thank you for your input. I will investigate further why some of those log messages are missing. I am guessing it has something to do with the fact that the image was built before `v2.4.0` . QQ you haven't had an opportunity to test the `TLS` settings have you?

And yes we are are having ongoing discussions about the issue your brought up about the custom hook functionality. I am thinking that for this first version we will just release a very basic image with just simple configuration, and create some tickets for adding proper functionality for `TLS` and whatever we choose for the `custom-hook` implementation.

**Reply by SimonMacIntyre** [reply]
That log file was only missing because I think I caused the docker image to explode (quietly) when it tried to bind to a port that I did not have available. That's my theory.. see my edits above with the strikeout! 

>One thing to note that isn't shown in that above file link is that for the TLS config there is indeed a config for the cacert in the form of "cacert_file"

Hmm how do i test it? In your example I see this part of the yaml:
```yaml
    tls:
      certfile: cert.crt
      keyfile: key.txt
```

Are you saying that I should call it, cacert_file instead? 

 I tried this:
 ```yaml
     tls:
      certfile: /etc/ssl/certs/cert.pem
      keyfile: /etc/ssl/certs/cert.pem
 ```

The server started, but I was not able to load my https 8080 dashboard. Also in the logs it said `ws` not `wss`, and `http` not `https` for the listeners. 

So I am probably misconfiguring something wrong here :thinking:

Here's what I'm using to test:
```yaml
server:
  hooks:
    allow_all: true
  listeners:
    healthcheck:
      port: 8081
    stats:
      port: 8080
    tcp:
      port: 8883
    websocket:
      port: 8882
    tls:
      certfile: /etc/ssl/certs/cert.pem
      keyfile: /etc/ssl/certs/cert.pem
  options:
    capabilities:
      maximum_message_expiry_interval: 100
      compatibilities:
        obscure_not_authorized: true

```

and docker compose:
```yaml
  mqtt2:
    image: dgduncan93/mochi-server-file-config:v0.0.1
    ports:
      - 8883:8883
      - 8882:8882
      - 8080:8080
    environment:
      VIRTUAL_HOST: mqtt.xrdm.docker
    networks:
      - xrdm-local
    volumes:
      - ~/.arborxr/certs/xrdm.docker.crt:/etc/ssl/certs/cert.pem:ro
      - ~/.arborxr/certs/xrdm.docker.key:/etc/ssl/certs/key.pem:ro
      - ./mochi_config.yml:/mochi_config.yml
```

One last thing, I noticed you mentioned:
>New "smart" defaults created such that if a user only adds a few config fields to the mochi_config.yml file, defaults are created for the other fields

I recently noticed when I defined a single capability in the object, that it no longer took the OTHER capability defaults. In particular, I wanted to only set session expiry interval, but a side effect of this was my `maximumReceive` becoming `0`! 

Looking through the code, it is not unreasonable, I just copied the default capability list entirely and changed my 1 or 2 values to get around it. But I wasn't sure if it was worth changing. Does your comment here do something similar? Because in your file config, if you did the same thing, I would have assumed it also would, for example, change maximumReceive to 0 in the absence of it being present.

**Reply by dgduncan** [reply]
> I recently noticed when I defined a single capability in the object, that it no longer took the OTHER capability defaults. In particular, I wanted to only set session expiry interval, but a side effect of this was my maximumReceive becoming 0!

Well if that is the case that is for sure not the intended outcome haha. I will look into that as well.

The config for TLS looks something like this: 
```
type TLS struct {
	Cert   string `yaml:"cert_file"`
	Key    string `yaml:"priv_key"`
	CACert string `yaml:"cacert_file"`
}
```
So the cert file is referenced via `cert_file`, key is `priv_key`, and CA cert is `cacert_file`
Also from your configuration, to enable TLS on a listener you have to use `tls_enabled: true` on that listener config just how it is done on the `tcp` part of [this](https://github.com/dgduncan/mqtt/blob/feature/basic-file-config/mochi_config.yml) example file  

Perhaps that is not the best way to do it; however, my idea is that if you configure TLS, there are many times in which you would not want to add it to every listener, so you have to explicitly set it to true to use.

**Reply by SimonMacIntyre** [reply]
First, I fixed some typos 🤦 
Now I have these 2 segments:
```yaml
    volumes:
      - ~/.arborxr/certs/xrdm.docker.crt:/etc/ssl/certs/cert.pem:ro
      - ~/.arborxr/certs/xrdm.docker.key:/etc/ssl/certs/key.pem:ro
      - ~/.arborxr/certs/rootCA.pem:/etc/ssl/cacert.pem:ro
      - ./mochi_config.yml:/mochi_config.yml
```

and in the config:
```yaml
    tcp:
      port: 8883
      tls_enabled: true
    websocket:
      port: 8882
      tls_enabled: true
    tls:
      cert_file: /etc/ssl/certs/cert.pem
      priv_key: /etc/ssl/certs/key.pem
      cacert_file: /etc/ssl/certs/cacert.pem
```

Great! Now here is the logs:
```text
2023-09-14 12:03:34 3:03PM INF added hook hook=allow-all-auth
2023-09-14 12:03:34 2023/09/14 15:03:34 INFO Certificate and Key information found in config step=config
2023-09-14 12:03:34 2023/09/14 15:03:34 INFO mochi_config.yml not found
2023-09-14 12:03:34 2023/09/14 15:03:34 INFO defaulting to standard broker configuration
2023-09-14 12:03:34 3:03PM INF added hook hook=allow-all-auth
2023-09-14 12:03:34 3:03PM INF attached listener address=:1883 id=t1 protocol=tcp
2023-09-14 12:03:34 3:03PM INF attached listener address=:1882 id=ws1 protocol=ws
2023-09-14 12:03:34 3:03PM INF attached listener address=:8080 id=stats protocol=http
```

What I find very confusing:
* it DOES find the mochi_config.yml, we know this because it finds the cert/key info in config, and it starts with the allow-all-auth at the very top
* something goes wrong? mochi_config.yml not found, one line after... presumably reading from that file


I'll see if I can find some human-error on my implementation side
