### ISSUE TITLE
How to allow specific username to read/write on a specific topic, and denied enything else?

### ISSUE THREAD

**Issue by hisamafahri** [mochi-mqtt/server#362]
I have the following `auth.yml` configuration:

```yaml
auth:
  - username: admin
    password: admin
    allow: true
  - username: client_1
    password: client_1
    allow: true

# 0 = deny, 1 = read only, 2 = write only, 3 = read and write
acl:
  - username: admin
    filters:
      '#': 3
  - username: client_1
    filters:
      '#': 0
      client_1/#: 3
```

The `client_1` cannot read or write to any topics.

If I remove ` '#': 0` from the `client_1` filters, now `client_1` filter can read/write to any topics.

Any idea on how to limit specific username to only able to read/write on a specific topic and denied the rest?
